### ISSUE TITLE
error on run appsody deploy

### ISSUE THREAD

**Issue by jaricsng** [kabanero-io/guide-collection-microprofile#14]
following the steps in cloud native with eclipse microprofile [here](https://kabanero.io/guides/collection-microprofile/#deploying-to-kubernetes) and encountered the error **_Error: Failed to synchronize cache for repo 'ubi-8-appstream'_** below running ```appsody deploy```

```
[Docker] Sending build context to Docker daemon  604.7kB
[Docker] Step 1/25 : FROM registry.access.redhat.com/ubi8/ubi
[Docker]  ---> 11f9dba4d1bc
[Docker] Step 2/25 : RUN yum upgrade --disableplugin=subscription-manager -y    && yum clean --disableplugin=subscription-manager packages    && echo 'Finished installing dependencies'
[Docker]  ---> Running in a663b006e990
[Docker] Red Hat Universal Base Image 8 (RPMs) - AppStre 0.0  B/s |   0  B     00:32
[Docker] Error: Failed to synchronize cache for repo 'ubi-8-appstream'
[Docker] The command '/bin/sh -c yum upgrade --disableplugin=subscription-manager -y    && yum clean --disableplugin=subscription-manager packages    && echo 'Finished installing dependencies'' returned a non-zero code: 1
[Error] exit status 1
```

advise?

**Comment by Charlotte-Holt** [comment]
@kilnerm It looks like the same issue over here as in https://github.com/kabanero-io/guide-collection-springboot2/issues/4.

**Comment by kilnerm** [comment]
@Charlotte-Holt Can the guide be updated to point at the latest Kabanero index in the getting started section:

```
https://github.com/kabanero-io/collections/releases/download/0.2.1/kabanero-index.yaml
```

**Comment by Charlotte-Holt** [comment]
@kilnerm I opened #24 to address this too.

**Comment by Charlotte-Holt** [comment]
@kilnerm @jaricsng This update is live at https://kabanero.io/guides/collection-microprofile/. Closing this issue.
