### ISSUE TITLE
appsodyhub is no longer used as a repo name by appsody

### ISSUE THREAD

**Issue by henrynash** [kabanero-io/guide-collection-microprofile#23]
appsody now uses the actual repo name (e.g. incubator) rather than appsodyhub. The current examples of `appsody repo list` still show appsodyhub.

**Comment by Charlotte-Holt** [comment]
@henrynash Thanks for pointing this out. I didn't see any specific instances of `appsodyhub` in the guide. Could you point out which examples need to be updated and what they need to be updated to?

**Comment by SueChaplain** [comment]
This issue is already fixed, see https://github.com/kabanero-io/guide-collection-microprofile/pull/21
Closing
