### ISSUE TITLE
Use the java-openliberty stack instead of the java-microprofile stack

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/guide-collection-microprofile#28]
Kabanero 0.6.0 officially deprecated the java-microprofile stack. The guide should use the java-openliberty stack instead.

Is the idea that this guide will be completely replaced by this guide?
https://github.com/kabanero-io/draft-guide-collection-java-openliberty

If, please close this issue.

**Comment by nastacio** [comment]
Related to kabanero-io/guide-codewind-getting-started#9
cc @scottkurz

**Comment by mingcyu** [comment]
Both Open Liberty and Eclipse Microprofile guides are live. This issue can be closed
